name: 'Build & Deploy to EKS'
on:
    # pull_request:
    #     branches: ["main"]

  workflow_dispatch:
      inputs:
          confirm:
              description: "Deploy application to EKS cluster? (y/n)"
              required: true
              default: 'n'
              type: choice
              options:
                  - 'y'
                  - 'n'
          release_tag:
              description: Enter release tag to deploy
              required: true
              type: string
                


env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  EKS_CLUSTER: ${{ vars.EKS_CLUSTER }}
  EKS_REGION: ${{ vars.EKS_REGION }}
  RELEASE_TAG: ${{ github.event.inputs.release_tag }}
  # IMAGE_TAG: "v3.0.0.7"
  
jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    env:
      ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'
    steps:
      # - name: Download Artifact
      #   uses: actions/download-artifact@v2
      #   with:
      #       name: AWS_ECR_TAG
      #       path: AWS_ECR_TAG.txt
      
      
        
      - uses: actions/checkout@v4

      - name: Validate entered release tag
        id: check-tag
        run: |
            if [[ ${{ env.RELEASE_TAG }} =~ ^v[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
                echo "match=true" >> $GITHUB_OUTPUT
            fi
            echo $match
            
      - name: Valid tag outcome
        if: steps.check-tag.outputs.match == true
        run: |
            echo "Release tag ${{ steps.check-tag.outputs.match }} is valid"
            
      - name: Parse validation results
        if: ${{ !steps.check-tag.outputs.match == true }}
        run: |
            echo "Release tag ${{ steps.check-tag.outputs.match }} is invalid"
            exit 1
      
      - name: search entered tag can be found in repo commit history
        id: match-tag
        run: |
          git fetch --tags
          echo "CONTAINS_TAG=$(git describe --tags --contains ${{ env.RELEASE_TAG }})" >> $GITHUB_OUTPUT
          echo $CONTAINS_TAG
          
      - name: parse search results
        if: ${{ !steps.check-tag.outputs.match == env.RELEASE_TAG }}
        # if: steps.match-tag.outputs.CONTAINS_TAG == "Could not get sha1 for ${{ env.RELEASE_TAG }}. Skipping."
        run: |
          echo "Input tag or release version is not found in the repository commit history"
          echo "Tag search yielded ${{ steps.match-tag.outputs.CONTAINS_TAG }}"
          exit 1
      
      
      - name: use non-prod values
        if: github.ref == 'refs/heads/develop'
        #  sed -i "s/<IMAGE_TAG>/v3.0.0.7/g" ./skaffold.yaml
        run: |
            EKS_NAMESPACE="dev"
            echo "IMAGE_TAG=${{ vars.NONPROD_IMAGE_NAME }}:${{ env.RELEASE_TAG }}" >> $GITHUB_ENV
            AWS_ECR_REG="255945442255.dkr.ecr.us-east-1.amazonaws.com/${{ vars.NONPROD_IMAGE_NAME }}"
            AWS_ECR_TAG="255945442255.dkr.ecr.us-east-1.amazonaws.com/${{ vars.NONPROD_IMAGE_NAME }}:${{ env.RELEASE_TAG }}"
            echo "$EKS_NAMESPACE"
            echo "$IMAGE_TAG"
            echo "$AWS_ECR_REG"
            echo "$AWS_ECR_TAG"
            sed -i "s|<PUBLIC_ECR_AWS>|$AWS_ECR_TAG|g" ./.k8s/flask-deployment-template.yml
            sed -i "s|<PUBLIC_ECR_AWS>|$AWS_ECR_REG|g" ./skaffold.yaml
            echo "EKS_NAMESPACE=$EKS_NAMESPACE" >> $GITHUB_ENV
            sed -i "s|<EKS_NAMESPACE>|$EKS_NAMESPACE|g" ./.k8s/flask-deployment-template.yml
            cat ./skaffold.yaml
            cat ./.k8s/flask-deployment-template.yml
            
      #   # replace ECR path and namespace - skaffold require tag and repo uri to be separate
      #   # but k8s deployment requires both repo uri and tag to be together 
      #   # AWS_ECR_TAG=$('255945442255.dkr.ecr.us-east-1.amazonaws.com/'${{ vars.NONPROD_IMAGE_NAME }}:${{ env.VER_TAG }}.${{ github.run_number }}\      
      - name: use prod values
        if: github.ref == 'refs/heads/main'
        run: |
            EKS_NAMESPACE="prod"
            echo "IMAGE_TAG=${{ vars.PROD_IMAGE_NAME }}:${{ env.RELEASE_TAG }}" >> $GITHUB_ENV
            AWS_ECR_REG="255945442255.dkr.ecr.us-east-1.amazonaws.com/${{ vars.PROD_IMAGE_NAME }}"
            AWS_ECR_TAG="255945442255.dkr.ecr.us-east-1.amazonaws.com/${{ vars.PROD_IMAGE_NAME }}:${{ env.RELEASE_TAG }}"
            echo "$EKS_NAMESPACE"
            echo "$IMAGE_TAG"
            echo "$AWS_ECR_REG"
            echo "$AWS_ECR_TAG"
            sed -i "s|<PUBLIC_ECR_AWS>|$AWS_ECR_TAG|g" ./.k8s/flask-deployment-template.yml
            sed -i "s|<PUBLIC_ECR_AWS>|$AWS_ECR_REG|g" ./skaffold.yaml
            sed -i "s/<IMAGE_TAG>/latest/g" ./skaffold.yaml
            echo "EKS_NAMESPACE=$EKS_NAMESPACE" >> $GITHUB_ENV
            sed -i "s|<EKS_NAMESPACE>|$EKS_NAMESPACE|g" ./.k8s/flask-deployment-template.yml
            cat ./skaffold.yaml
            cat ./.k8s/flask-deployment-template.yml
      
      - uses: actions/setup-python@v5
        with:
         python-version: '3.12'
         cache: 'pip'
      - run: pip install -r ./requirements.txt

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with: 
            # parameters of configure aws credentials
            aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
            aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY}}
            aws-region: us-east-1
            
      
      # Install kubectl
      - name: Install kubectl
        run: |
          curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
          curl -LO "https://dl.k8s.io/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl.sha256"
          echo "$(<kubectl.sha256) kubectl" | sha256sum --check


          sudo install -o root -g root -m 0755 kubectl /usr/local/bin/kubectl
          kubectl version --client
      # Install Skaffold
      - name: Install Skaffold
        run: |
          curl -Lo skaffold https://storage.googleapis.com/skaffold/releases/latest/skaffold-linux-amd64 && \
          sudo install skaffold /usr/local/bin/
          skaffold version
      # Cache skaffold image builds & config
      - name: Cache skaffold image builds & config
        uses: actions/cache@v2
        with:
          path: ~/.skaffold/
          key: fixed-${{ github.sha }}
      # Check AWS version and configure profile
      - name: Check AWS version
        run: |
          aws --version
          aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
          aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
          aws configure set region $EKS_REGION
          aws sts get-caller-identity
      # login to ecr - skaffold will build and push image to repo too 
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
      # Connect to EKS cluster
      - name: Connect to EKS cluster 
        run: aws eks --region $EKS_REGION update-kubeconfig --name $EKS_CLUSTER
        
      # Build and deploy to EKS cluster
      - name: Deployment to  EKS cluster with Skaffold
        run: |
            skaffold deploy --images=255945442255.dkr.ecr.us-east-1.amazonaws.com/${{ env.IMAGE_TAG }}
            echo "deployed ${{ env.IMAGE_TAG }} to eks cluster"
            
      # Replace the hostname of ingress service with load balancer address
      # - name: Replace the hostname of ingress service with load balancer address
      #   run: |
      #       LB_HOST=$(kubectl get svc nginx-ingress-ingress-nginx-controller -n kube-system -o jsonpath='{.status.loadBalancer.ingress[0].hostname}')
      #       sed -i 's/<ENDPOINT>/$LB_HOST' ./.k8s/ngix-ingress-template.yaml > ./.k8s/ngix-ingress.yaml
      #       kubectl apply -f ./.k8s/ngix-ingress.yaml
      

      # Verify deployment
      - name: Verify the deployment
        run: kubectl get pods
